[package]
name = "image-app"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.25"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
